NC upload
TURMObs/TURMFrontend pull request #10
Opened 2024-11-26 16:54 UTC by WickAJ

This extends the functionality of nextcloud_manager.py. It is now possible to delete files from a nextcloud and to upload/download dictionaries without intermediate storing necessary.

Also includes nextcloud_upload.py which is responsible for uploading new observations from the DB to the nextcloud.

2024-12-03 18:25 UTC, btw04 requested changes

2024-12-03 18:25 UTC, btw04 commented on nextcloud/tests.py
> +dict_nc = "dict1.json"
All of these test files are not tracked in the repository (but should be)

2024-12-11 21:03 UTC, bennetbo commented on .DS_Store
This should be removed

2024-12-11 21:04 UTC, bennetbo commented on .gitignore
> -.DS_Store
This should not be removed

2024-12-11 21:05 UTC, bennetbo commented
Seems like [3778234](https://github.com/TURMObs/TURMFrontend/pull/10/commits/3778234dfae1f6e5d42ad1e342f11af246f57ee1) reverted a lot of stuff which we removed before.

2024-12-14 12:19 UTC, btw04 requested changes

2024-12-14 12:19 UTC, btw04 commented on nextcloud/nextcloud_sync.py
> +    return s
It is bad practice to name variables like this

2024-12-14 12:19 UTC, btw04 commented on nextcloud/management/commands/sync_nextcloud.py
> +            self.stdout.write(self.style.ERROR(f"Error uploading observations: {e}"))
This seems like duplicate logging

2024-12-14 12:19 UTC, btw04 commented on nextcloud/nextcloud_manager.py
> +    Uploads a file to the Nextcloud server. Overwrites any existing file with same path+name in nextcloud. Directory that should contain the file must already exist.
This function should probably throw an exception instead of silently overwriting existing files. At least make it a parameter (i.e. `overwrite=True`)

2024-12-14 12:19 UTC, btw04 commented on nextcloud/nextcloud_manager.py
> +    Uploads a file_stream to the Nextcloud. Overwrites any existing file with same path+name in nextcloud. Directory that should contain the file must already exist.
`file_stream` should be `dict`

2024-12-14 12:19 UTC, btw04 commented on nextcloud/nextcloud_manager.py
> +    :param indent: Number of spaces per indent
Could be explained better

2024-12-14 12:19 UTC, btw04 commented on nextcloud/nextcloud_manager.py
> +    """
Needs stronger wordings. This function should absolutely never be called outside of a testing environment. It might actually check whether it is run inside a test

2024-12-14 12:19 UTC, btw04 commented on nextcloud/nextcloud_manager.py
> +        path = "/".join(dirs[:i])
This can probably be handled better

2024-12-14 12:19 UTC, btw04 commented on nextcloud/nextcloud_sync.py
> +It is supposed to run in a cron-Job
*to be triggered by a

2024-12-14 12:19 UTC, btw04 commented on nextcloud/nextcloud_sync.py
> +    return accepted_amount / required_amount
The result should probably be rounded

2024-12-14 12:19 UTC, btw04 commented on nextcloud/nextcloud_sync.py
> +"""
Clean this up if the scope of the PR is only supposed to be the Upload

2024-12-14 12:19 UTC, btw04 commented on nextcloud/nextcloud_sync.py
> +    )  # exclude ScheduledObservation. They are handled explicit
Unnecessary comment

2024-12-14 12:19 UTC, btw04 commented on nextcloud/test_data/upload_file.json
Why is this file needed?

2024-12-14 12:19 UTC, btw04 commented on nextcloud/tests.py
> +):
If all your tests do not change these variables, why are they exposed as parameters? These can just be hardcoded in the creation process, and only the necessary fields exposed (i.e. project_status)

2024-12-14 12:19 UTC, btw04 commented on nextcloud/tests.py
> +    Checks if observation exists in nextcloud. Work by trying to download the observation.
Typo

2024-12-14 12:19 UTC, btw04 commented on nextcloud/tests.py
> +    return True
This is a very bad way of handling this. Adds a lot of overhead

2024-12-14 12:19 UTC, btw04 commented on nextcloud/tests.py
> +            return obs
Use `objects.filter` instead

2024-12-14 12:19 UTC, btw04 commented on nextcloud/tests.py
> +        nm.delete("delete_test.json")
Why is the upload needed here?

2024-12-14 12:19 UTC, btw04 commented on nextcloud/tests.py
> +            self.assertRaises(NextcloudException)
This test succeeds if an exception is thrown?

2024-12-14 12:19 UTC, btw04 commented on nextcloud/tests.py
> +        nm._delete_all()
Why is the upload needed here?

2024-12-14 12:19 UTC, btw04 commented on nextcloud/tests.py
> +
The setUp should be the first method of the class

2024-12-14 12:19 UTC, btw04 commented on nextcloud/tests.py
> +                nm.delete(get_nextcloud_path(obs))
Please implement a good `exists_in_nc` function

2024-12-14 12:19 UTC, btw04 commented on nextcloud/tests.py
> +
This does not assure that the correct Requests were uploaded

2024-12-14 12:19 UTC, btw04 commented on nextcloud/tests.py
> +        assert_equal(2, observations_day0.count())
Do not use count here

2024-12-14 12:19 UTC, btw04 commented on observation_data/models.py
>      end_scheduling = models.DateTimeField()
This should be removed

2024-12-14 15:01 UTC, WickAJ commented on nextcloud/nextcloud_sync.py
> +    # get the name of the project. Inefficient to get serializer again, but prevents necessity of another argument
Offset is not required but makes more versatile. Therefore it has a reasonable default value.

2024-12-14 15:08 UTC, WickAJ commented on nextcloud/nextcloud_sync.py
> +    return s
was for debugging purposes, will be removed

2024-12-14 15:20 UTC, WickAJ commented on nextcloud/tests.py
> +):
Although they are currently not used, they might be required in the future. Setting default parameters allow for easy adjustments in the future.

2024-12-14 15:26 UTC, WickAJ commented on nextcloud/tests.py
> +        nm.delete("delete_test.json")
Small changes, now method body looks like: 
nm.upload_file("delete_test.json", file_upload)
nm.delete("delete_test.json")
self.assertRaises(nm.delete("delete_test.json"))

First the file is uploaded.
Then it is deleted. If the file was not correctly uploaded, this throws an error and fails the test.
The second delete tries to delete a file that should not exist since the file was deleted by the first delete and is therefore expected to throw an Exception

2024-12-14 15:29 UTC, WickAJ commented on nextcloud/tests.py
> +            self.assertRaises(NextcloudException)
Don't know what I did there.

2024-12-14 15:30 UTC, WickAJ commented on nextcloud/tests.py
> +        nm._delete_all()
Leftover artefact

2024-12-14 15:38 UTC, WickAJ commented on nextcloud/tests.py
> +
Actually in this case it does, but I will rewrite the test anyway.

2024-12-14 15:38 UTC, WickAJ commented on nextcloud/tests.py
> +        assert_equal(2, observations_day0.count())
Why not. I works as intended

2024-12-14 15:40 UTC, WickAJ commented on observation_data/models.py
>      end_scheduling = models.DateTimeField()
You are right. Unfortunately I don't know who is responsible for the DB modeling.

2024-12-17 13:04 UTC, btw04 approved these changes
Some small grammar changes, but the implementations seem good and well tested

2024-12-17 13:04 UTC, btw04 commented on nextcloud/nextcloud_manager.py
> +    :param overwrite_existing: Whether to overwrite a file with same path already exists
grammar

2024-12-17 13:04 UTC, btw04 commented on nextcloud/nextcloud_manager.py
> +    :param overwrite_existing: Whether to overwrite a file with same path already exists
grammar

2024-12-18 12:20 UTC, merged