Add dashboard
TURMObs/TURMFrontend pull request #14
Opened 2024-11-28 15:00 UTC by bennetbo

This adds a dashboard to the app, where users will be able to see their observation requests. This is also where we expose links to other functionality, like logging out or creating observation requests.

<img width="1609" alt="image" src="https://github.com/user-attachments/assets/300c06ba-85ff-4fe9-b471-35944213927d">

2024-12-01 21:06 UTC, bennetbo commented
There is not a "clear" stopping point for when this is completed. Right now all the added functionality should work and existing functionality should still work/be as broken as before.

I would like to get my changes in now, so that everyone can keep iterating with the new approach (and get rid of the demo code which we had before).
A couple follow ups include:
- Come up with a new user invitation view, which removes the old `generate_invitation.html
- Redesign the `register_from_invitation.html` similar to what we have for login
- Actually write new observation request to the database
- Add an overview of submitted observations

2024-12-03 17:54 UTC, btw04 requested changes
Agreed on merging this ASAP. Requested changes are minor

2024-12-03 17:54 UTC, btw04 commented on authentication/views.py
> +    return redirect("dashboard")
This could also be an entry in `settings.py` IMO

2024-12-03 17:54 UTC, btw04 commented on authentication/views.py
> +    return redirect("dashboard")
See comment above.

2024-12-03 17:54 UTC, btw04 commented on observation_request/views.py
> +    return HttpResponse(request.data.dict())
This seems unrelated

2024-12-03 17:55 UTC, btw04 commented
And please add the potential follow ups to the backlog on Trello. We might want a different category for these kind of "potentials" that aren't necessarily a fit for our backlog

2024-12-04 12:06 UTC, bennetbo commented on observation_request/views.py
> +    return HttpResponse(request.data.dict())
Now that we require login by default, accessing body breaks. That's why I changed it

2024-12-04 12:11 UTC, btw04 approved these changes
LGTM

2024-12-04 12:12 UTC, merged