Observation request filter set
TURMObs/TURMFrontend pull request #25
Opened 2024-12-13 09:56 UTC by SprangerjS

2024-12-13 11:16 UTC, btw04 commented
Please provide a description

2025-01-15 21:07 UTC, Keyscha requested changes

2025-01-15 21:07 UTC, Keyscha commented on static/js/turminputs.js
> +function discard_input(event, el, suppressed) {
Please add comments to increase clarity

2025-01-15 21:07 UTC, Keyscha commented on static/js/turminputs.js
> +            // add hover notice
Leftover comment? Or write To do:

2025-01-16 10:37 UTC, SprangerjS commented on static/css/base_template.css
> +button, input[type='submit'] {
war ich auch am überlegen, das hätte ich mit dir in dem style consolidation besprochen (das selbe gilt für den hintergrund). Meine überlegung war das jeder butten erstmal unser basic styling bekommen sollte, das kann man ja immer überschreiben. Bin aber auch fine wenn wir das in eine classe refactorn

2025-01-16 10:37 UTC, SprangerjS commented on static/css/base_template.css
> +button:hover, input[type='submit']:hover {
siehe oben

2025-01-16 10:42 UTC, SprangerjS commented on observation_request/TURMField.py
> +        self.required = False
Choice input impliziert ja das einem freigestellt wird ob man es auswählt oder nicht. Wäre required nicht auf false müsste man jeden filter auswählen um ein request zu erstellen.
Die funktionalität _required_ wird von den Django _form.fields_ bereitgestellt. Man kann also auch einfach andere erstellte Fields disablen. Das macht aber sonst nur für objekte und nicht klassen sinn.

2025-01-16 10:46 UTC, SprangerjS commented on observation_request/TURMInput.py
> +from django.forms import Widget
Ich mags auch nicht, ist der Django way

2025-01-16 10:51 UTC, SprangerjS commented on observation_data/views.py
> +        logger.warning("entered remapping")
@btw04

2025-01-16 10:52 UTC, SprangerjS commented on observation_data/views.py
> +    logger.warning("serializer not valid")
@btw04

2025-01-16 10:55 UTC, SprangerjS commented on static/css/base_template.css
> +    background: url(../img/HeartNebula.jpg) no-repeat;
siehe oben

2025-01-16 13:04 UTC, btw04 requested changes

2025-01-16 13:04 UTC, btw04 commented on observation_data/forms.py
> +    except RuntimeError as e:  # todo: Specify the Error
Please implement this todo

2025-01-17 08:34 UTC, bennetbo commented on observation_request/TURMInput.py
> +from django.forms import Widget
Just to clarify, `TURMField.py` defines the Fields (base class `Field`), which are abstract representations of the data. `TURMInput.py` defines the widgets (base class `Widget`) which actually determine how a specific field should be rendered (generates HTML)

2025-01-19 19:43 UTC, btw04 approved these changes
LGTM

2025-01-19 22:10 UTC, Keyscha commented on static/css/base_template.css
> +button, input[type='submit'] {
Let's leave it for now and see if we run into any issues

2025-01-19 22:10 UTC, Keyscha approved these changes

2025-01-19 22:10 UTC, merged